version: 2

references:
  workspace: &workspace
    ~/sticky-sessions-android

  config_android: &config_android
    working_directory: *workspace
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JAVA_TOOL_OPTIONS: "-Xms1024m -Xmx3200m"

  cache_key: &cache_key
    key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      root: .
      paths:
        - ftl-tests
        - build
        - app/build
        - distribution
        - fastlane
        - changelog.txt
        - Gemfile

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace

jobs:
  build:
    <<: *config_android

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          name: Store Firebase Key
          command: echo $GOOGLE_SERVICES > ~/sticky-sessions-android/app/google-services.json

      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle

      - run:
          name: Run Lint and Unit tests
          command: ./gradlew lintProdRelease testProdReleaseUnitTest

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - run:
          name: Build
          command: ./gradlew clean assembleProdRelease --no-daemon --stacktrace

      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/

      - *persist_to_workspace

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
